version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  chroma:
    image: chroma:latest
    container_name: chroma_container
    environment:
      CHROMA_USER: user
      CHROMA_PASSWORD: password
    ports:
      - "8080:8080"

volumes:
  postgres_data:
